# Generated by Django 5.0.6 on 2024-07-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_product_remain_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remain',
            field=models.PositiveIntegerField(verbose_name='Остаток'),
        ),
    ]
